//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	words, _ := os.ReadFile("wordlist.txt")
	wordList := strings.Split(string(words), "\n")
	fmt.Print("Generate words array from wordlist.txt\n\n")
	wordCount := len(wordList)
	out := "package seedphrase\n"
	out += "// This file autogenerated. Please don't edit!\n"
	out += "\nfunc init() {\n\tfor i, word := range words {\n\t\twordsIndex[word] = uint16(i)\n\t}\n}\n\n"
	out += "var (\n\twordsIndex = make(map[string]uint16)\n words = [" + fmt.Sprintf("%d", wordCount) + "]string{\n"
	for _, word := range wordList {
		out += "\t\"" + word + "\",\n"
	}
	out += "}\n)\n"
	os.WriteFile("words.go", []byte(out), 0644)
}
